# Generated by Django 2.0 on 2018-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
