# Generated by Django 2.0 on 2018-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mili', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='percent',
            field=models.PositiveIntegerField(),
        ),
    ]
