# Generated by Django 2.0 on 2018-09-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mili', '0002_auto_20180930_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('roll', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('chest', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('pull_ups', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
            ],
        ),
    ]
