# Generated by Django 2.0 on 2018-10-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mili', '0003_examination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='state',
            new_name='roll',
        ),
    ]
