# Generated by Django 2.0 on 2018-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mili', '0004_auto_20181001_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='roll',
            field=models.CharField(max_length=5),
        ),
    ]
