# Generated by Django 2.0 on 2018-10-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mili', '0005_auto_20181001_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_check_delete', models.PositiveIntegerField()),
            ],
        ),
    ]
