# Generated by Django 2.0 on 2018-10-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mili', '0006_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
