# Generated by Django 2.0 on 2018-10-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mili', '0007_delete_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='name',
        ),
        migrations.AlterField(
            model_name='examination',
            name='roll',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.PositiveIntegerField(choices=[(18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registration',
            name='roll',
            field=models.CharField(max_length=6),
        ),
    ]
