# Generated by Django 2.0 on 2018-11-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='DetailView',
        ),
    ]
