# Generated by Django 2.0 on 2018-11-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20181103_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Informations',
        ),
    ]
